export type ScreenParamLists = {
  Home: undefined;
  Profile: undefined;
  MyCourse: undefined;
  MyResults: undefined;
  MyFees: undefined;
  PaymentInfo: undefined;
  FeesDetails: {item: object};
  CourseRegistration: undefined;
  Project: undefined;
  ELibrary: undefined;
  ExamRegistration: undefined;
  Academic: undefined;
  Timetable: undefined;
  Calendar: undefined;
  AcademicSession: undefined;
  Faculties: undefined;
  Curriculum: undefined;
  Assignment: undefined;
  TimetableOption: undefined;
  EditTimetable: {time: string};
  EditCalendar: {item: object};
  FacultyCourses: {item: object};
  CurriculumLevel: {item: object};
  CurriculumDetails: {item: object; lev: object};
  EditCourses: {item: object};
  EditAssignment: undefined;
  Reception: undefined;
  AdmissionEnquiry: undefined;
  AdmissionEnquiryDetails: undefined;
  EditAdmissionEnquiry: undefined;
  VisitorLog: undefined;
  CallLog: undefined;
  Complaint: undefined;
  EditVisitorLog: undefined;
  Students: undefined;
  StudentProfile: {item: object};
  BasicInformation: {item: object};
  ParentInformation: {item: object};
  ContactInformation: {item: object};
  DocumentInformation: {item: object};
  ManageFees: {item: object};
  ManageResults: {item: object};
  StudentResult: {item: object};
  Staffs: undefined;
  StaffProfile: {item: object};
  Exams_Records: undefined;
  ResultDetails: {item: object};
  ResultAttendance: undefined;
};
